### PR TITLE
Added Charts and Ties

### PR DESCRIPTION
**Pull request by Dbz**
Added Google Charts through the Chartkick gem
+ Added chart to track daily progress on game show page
+ Added chart to track all user progress on player game show page

Added Ties
+ Added ties column to game show page when ties are part of the game type
+ Added ties column to player game show page when ties are part of the game type

Minor CSS changes
+ Removed a body border-bottom that did not stick to the bottom of the page

### CODE REVIEW

**Comment by drewolson** [comment]
Thanks for the PR @Dbz. I'm definitely looking for test coverage for any of the backend code, but don't feel the need to test the frontend changes.

**Comment by Dbz** [comment]
@drewolson I added specs to test all of the backend components I added/modified. I didn't test the `@chart_data` variable I created in the games controller and in the player games controller, but everything else is covered. I didn't see any tests for other controller variables, and I ran into trouble with `assigns()` when attempting to test it, but let me know if you want tests for it- otherwise this is ready to be merged. I think you will like the addition of charts and proper handling of ties!

**Comment by drewolson** [comment]
I'll take a look at this in the next few days, thanks!

**Comment by Dbz** [comment]
Awesome! Thank you. Let me know if I need to make any changes.

**Comment by drewolson** [comment]
All merged. Thanks again!

**Pull request merged**
